# Generated by Django 5.2.11 on 2026-02-05 17:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="brands/")),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MpesaAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[("SANDBOX", "Sandbox"), ("PRODUCTION", "Production")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("consumer_key", models.CharField(max_length=200)),
                ("consumer_secret", models.CharField(max_length=200)),
                ("shortcode", models.CharField(max_length=20)),
                ("passkey", models.TextField()),
                ("initiator_name", models.CharField(blank=True, max_length=100)),
                ("initiator_password", models.TextField(blank=True)),
                ("certificate_path", models.CharField(blank=True, max_length=500)),
                ("callback_base_url", models.URLField(blank=True)),
                ("stk_callback_url", models.URLField(blank=True)),
                ("c2b_validation_url", models.URLField(blank=True)),
                ("c2b_confirmation_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("auto_register_urls", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "M-Pesa Configuration",
                "verbose_name_plural": "M-Pesa Configurations",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField(blank=True)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                ("payment_terms", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(default=uuid.uuid4, max_length=20, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("REG", "Regular"),
                            ("SIL", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLAT", "Platinum"),
                            ("VIP", "VIP"),
                        ],
                        default="REG",
                        max_length=4,
                    ),
                ),
                ("loyalty_points", models.IntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_purchase", models.DateTimeField(blank=True, null=True)),
                ("preferred_payment", models.CharField(default="CASH", max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_number",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("UTILITIES", "Utilities"),
                            ("SALARIES", "Salaries"),
                            ("MARKETING", "Marketing"),
                            ("MAINTENANCE", "Maintenance"),
                            ("OFFICE", "Office Supplies"),
                            ("TRANSPORT", "Transport"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MPESA", "M-Pesa"),
                            ("CARD", "Card"),
                            ("BANK", "Bank Transfer"),
                            ("LOYALTY", "Loyalty Points"),
                            ("MIXED", "Mixed Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("receipt", models.FileField(blank=True, upload_to="expenses/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("merchant_request_id", models.CharField(blank=True, max_length=50)),
                ("checkout_request_id", models.CharField(blank=True, max_length=50)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("STK_PUSH", "STK Push"),
                            ("C2B", "Customer to Business"),
                            ("B2C", "Business to Customer"),
                            ("REVERSAL", "Reversal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("phone_number", models.CharField(max_length=15)),
                ("account_reference", models.CharField(max_length=50)),
                ("transaction_desc", models.CharField(max_length=100)),
                ("mpesa_receipt_number", models.CharField(blank=True, max_length=50)),
                ("result_code", models.IntegerField(blank=True, null=True)),
                ("result_description", models.TextField(blank=True)),
                ("response_code", models.CharField(blank=True, max_length=10)),
                ("response_description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("raw_request", models.JSONField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaCallback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "callback_type",
                    models.CharField(
                        choices=[
                            ("STK", "STK Push Callback"),
                            ("C2B", "C2B Validation/Confirmation"),
                            ("B2C", "B2C Result"),
                            ("BALANCE", "Balance Result"),
                            ("REVERSAL", "Reversal Result"),
                            ("STATUS", "Transaction Status Result"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_data", models.JSONField()),
                ("result_code", models.IntegerField(blank=True, null=True)),
                ("result_description", models.TextField(blank=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_notes", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.mpesatransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Low Stock"),
                            ("EXPIRY", "Expiry Alert"),
                            ("SALE", "New Sale"),
                            ("PURCHASE", "Purchase Order"),
                            ("SYSTEM", "System Alert"),
                            ("CUSTOMER", "Customer Activity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=50, unique=True, verbose_name="SKU"),
                ),
                ("barcode", models.CharField(blank=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("SKIN", "Skincare"),
                            ("HAIR", "Haircare"),
                            ("MAKE", "Makeup"),
                            ("FRAG", "Fragrance"),
                            ("BATH", "Bath & Body"),
                            ("TOOL", "Tools & Accessories"),
                            ("MENS", "Men's Grooming"),
                            ("SUN", "Sun Care"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("low_stock_threshold", models.IntegerField(default=10)),
                ("reorder_quantity", models.IntegerField(default=25)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, upload_to="profiles/"),
                ),
                ("role", models.CharField(default="Staff", max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("hire_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                ("expected_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("ORDERED", "Ordered"),
                            ("RECEIVED", "Partially Received"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.supplier"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("received_quantity", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=16, max_digits=5),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "change_given",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MPESA", "M-Pesa"),
                            ("CARD", "Card"),
                            ("BANK", "Bank Transfer"),
                            ("LOYALTY", "Loyalty Points"),
                            ("MIXED", "Mixed Payment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Payment"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("PARTIAL", "Partially Refunded"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("mpesa_receipt", models.CharField(blank=True, max_length=50)),
                ("mpesa_transaction_id", models.CharField(blank=True, max_length=50)),
                ("mpesa_phone", models.CharField(blank=True, max_length=15)),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("loyalty_points_used", models.IntegerField(default=0)),
                ("loyalty_points_earned", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mpesatransaction",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mpesa_transactions",
                to="core.sale",
            ),
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_sku", models.CharField(max_length=50)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Stock Purchase"),
                            ("SALE", "Sale"),
                            ("ADJUSTMENT", "Stock Adjustment"),
                            ("RETURN", "Customer Return"),
                            ("DAMAGE", "Damaged Goods"),
                            ("TRANSFER", "Stock Transfer"),
                            ("EXPIRED", "Expired Goods"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("previous_quantity", models.IntegerField()),
                ("new_quantity", models.IntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="core_custom_email_899d12_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="core_custom_phone_cf7ec3_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["membership_type"], name="core_custom_members_36f41a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesacallback",
            index=models.Index(
                fields=["callback_type"], name="core_mpesac_callbac_d7092e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesacallback",
            index=models.Index(
                fields=["is_processed"], name="core_mpesac_is_proc_b6b9f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesacallback",
            index=models.Index(
                fields=["received_at"], name="core_mpesac_receive_6bf911_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["invoice_number"], name="core_sale_invoice_873e90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["created_at"], name="core_sale_created_3b2a6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["status"], name="core_sale_status_c7c270_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer"], name="core_sale_custome_07bccc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["transaction_id"], name="core_mpesat_transac_e7ff56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["checkout_request_id"], name="core_mpesat_checkou_04077c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["mpesa_receipt_number"], name="core_mpesat_mpesa_r_364745_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["phone_number"], name="core_mpesat_phone_n_9bdeea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(fields=["status"], name="core_mpesat_status_42d944_idx"),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["created_at"], name="core_mpesat_created_87d042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["product", "created_at"], name="core_stockt_product_4bb5b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["transaction_type"], name="core_stockt_transac_be70c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="core_produc_sku_a1eae6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="core_produc_barcode_5cc7aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="core_produc_name_be3252_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="core_produc_categor_784c92_idx"
            ),
        ),
    ]
