# Generated by Django 5.2.11 on 2026-02-23 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="paystack_access_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sale",
            name="paystack_authorization_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sale",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("MPESA", "M-Pesa"),
                    ("PAYSTACK", "Paystack"),
                    ("CARD", "Card"),
                    ("BANK", "Bank Transfer"),
                    ("LOYALTY", "Loyalty Points"),
                    ("MIXED", "Mixed Payment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("MPESA", "M-Pesa"),
                    ("PAYSTACK", "Paystack"),
                    ("CARD", "Card"),
                    ("BANK", "Bank Transfer"),
                    ("LOYALTY", "Loyalty Points"),
                    ("MIXED", "Mixed Payment"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PaystackTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("access_code", models.CharField(blank=True, max_length=100)),
                ("authorization_code", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Successful"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payment_status", models.CharField(blank=True, max_length=20)),
                ("authorization_url", models.URLField(blank=True)),
                ("access_code_url", models.URLField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("customer_code", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sale",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paystack_transaction",
                        to="core.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reference"], name="core_paysta_referen_89ea89_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_paysta_status_8e7c72_idx"
                    ),
                    models.Index(fields=["email"], name="core_paysta_email_9449f3_idx"),
                    models.Index(
                        fields=["created_at"], name="core_paysta_created_551e4d_idx"
                    ),
                ],
            },
        ),
    ]
