# Generated by Django 5.2.11 on 2026-02-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_sale_paystack_access_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="show_on_shop",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
