# Generated by Django 5.2.11 on 2026-02-05 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("metric", models.CharField(max_length=100)),
                ("target", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(max_length=50)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("weight", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=500, unique=True)),
                ("data", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cache_key"], name="analytics_a_cache_k_9a5fb4_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="analytics_a_expires_4e35a3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("REVENUE", "Revenue"),
                            ("PROFIT", "Profit"),
                            ("TRANSACTIONS", "Transactions"),
                            ("AVG_TICKET", "Average Ticket Size"),
                            ("CONVERSION", "Conversion Rate"),
                            ("CUSTOMER_COUNT", "Customer Count"),
                            ("LOYALTY", "Loyalty Points"),
                            ("INVENTORY_TURNOVER", "Inventory Turnover"),
                            ("GROSS_MARGIN", "Gross Margin"),
                            ("NET_MARGIN", "Net Margin"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "growth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period_date", "metric_type"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "period_date"],
                        name="analytics_b_metric__97a063_idx",
                    ),
                    models.Index(
                        fields=["period", "period_date"],
                        name="analytics_b_period_95473e_idx",
                    ),
                ],
                "unique_together": {("metric_type", "period", "period_date")},
            },
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("SALES", "Sales"),
                            ("DEMAND", "Demand"),
                            ("REVENUE", "Revenue"),
                            ("INVENTORY", "Inventory"),
                            ("EXPENSES", "Expenses"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("MOVING_AVERAGE", "Moving Average"),
                            ("EXPONENTIAL_SMOOTHING", "Exponential Smoothing"),
                            ("ARIMA", "ARIMA"),
                            ("LINEAR_REGRESSION", "Linear Regression"),
                            ("SEASONAL", "Seasonal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("forecast_date", models.DateField()),
                (
                    "forecast_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "confidence_interval_lower",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "confidence_interval_upper",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["forecast_type", "-forecast_date"],
                "unique_together": {("forecast_type", "period", "forecast_date")},
            },
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("SALES", "Sales Report"),
                            ("PRODUCT", "Product Performance"),
                            ("CUSTOMER", "Customer Analysis"),
                            ("INVENTORY", "Inventory Report"),
                            ("FINANCIAL", "Financial Report"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
                ("columns", models.JSONField(default=list)),
                ("sorting", models.JSONField(default=dict)),
                ("chart_config", models.JSONField(blank=True, default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("EXCEL", "Excel"),
                            ("CSV", "CSV"),
                            ("HTML", "HTML"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                (
                    "recipients",
                    models.TextField(help_text="Comma-separated email addresses"),
                ),
                ("next_run", models.DateTimeField()),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.savedreport",
                    ),
                ),
            ],
            options={
                "ordering": ["next_run"],
            },
        ),
        migrations.CreateModel(
            name="UserDashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Light"),
                            ("DARK", "Dark"),
                            ("AUTO", "Auto"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "default_period",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("quarter", "Quarter"),
                            ("year", "Year"),
                        ],
                        default="month",
                        max_length=20,
                    ),
                ),
                ("refresh_interval", models.IntegerField(default=300)),
                ("show_animations", models.BooleanField(default=True)),
                ("show_tooltips", models.BooleanField(default=True)),
                ("default_currency", models.CharField(default="KES", max_length=10)),
                ("number_format", models.CharField(default="en-KE", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("SALES_CHART", "Sales Chart"),
                            ("REVENUE_CARD", "Revenue Card"),
                            ("TOP_PRODUCTS", "Top Products"),
                            ("RECENT_SALES", "Recent Sales"),
                            ("LOW_STOCK", "Low Stock Alert"),
                            ("CUSTOMER_METRICS", "Customer Metrics"),
                            ("PROFIT_CHART", "Profit Chart"),
                            ("INVENTORY_VALUE", "Inventory Value"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=4)),
                ("height", models.IntegerField(default=4)),
                ("settings", models.JSONField(default=dict)),
                ("is_visible", models.BooleanField(default=True)),
                ("refresh_interval", models.IntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position_y", "position_x"],
                "unique_together": {("user", "widget_type")},
            },
        ),
    ]
